import { SuperAgentRequest } from 'superagent'
import { stubFor } from '../../wiremock'
import { IntegrityOrderDetails } from '../../../../server/data/models/integrityOrderDetails'

const defaultOrders: IntegrityOrderDetails[] = [
  {
    legacySubjectId: '1000000',
    firstName: 'Amy',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: null,
    dateOfBirth: '01-01-1970',
    orderStartDate: '08-02-2019',
    orderEndDate: '08-02-2020',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '2000000',
    firstName: 'Bill',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: 'Plato',
    dateOfBirth: '01-02-1971',
    orderStartDate: '03-11-2020',
    orderEndDate: '03-11-2021',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '3000000',
    firstName: 'Claire',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: null,
    dateOfBirth: '09-04-1962',
    orderStartDate: '05-08-2001',
    orderEndDate: '05-08-2002',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '8000000',
    firstName: 'Daniel',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: 'Aristotle',
    dateOfBirth: '12-11-1978',
    orderStartDate: '18-02-2012',
    orderEndDate: '18-02-2014',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '30000',
    firstName: 'Emma',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: 'Socrates',
    dateOfBirth: '03-03-2001',
    orderStartDate: '24-01-2017',
    orderEndDate: '24-01-2020',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '4000000',
    firstName: 'Fred',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: null,
    dateOfBirth: '08-10-1980',
    orderStartDate: '01-05-2021',
    orderEndDate: '01-05-2022',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '30000',
    firstName: 'Geoff',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: 'Socrates',
    dateOfBirth: '03-03-2001',
    orderStartDate: '24-01-2017',
    orderEndDate: '24-01-2020',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '4000000',
    firstName: 'Hortense',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: null,
    dateOfBirth: '08-10-1980',
    orderStartDate: '01-05-2021',
    orderEndDate: '01-05-2022',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '30000',
    firstName: 'Isaac',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: 'Socrates',
    dateOfBirth: '03-03-2001',
    orderStartDate: '24-01-2017',
    orderEndDate: '24-01-2020',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '4000000',
    firstName: 'Jessica',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: null,
    dateOfBirth: '08-10-1980',
    orderStartDate: '01-05-2021',
    orderEndDate: '01-05-2022',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '30000',
    firstName: 'Ken',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: 'Socrates',
    dateOfBirth: '03-03-2001',
    orderStartDate: '24-01-2017',
    orderEndDate: '24-01-2020',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
  {
    legacySubjectId: '4000000',
    firstName: 'Lucille',
    lastName: 'Smith',
    primaryAddressLine1: 'First line of address',
    primaryAddressLine2: 'Second line of address',
    primaryAddressLine3: 'Third line of address',
    primaryAddressPostCode: 'PostCode',
    alias: null,
    dateOfBirth: '08-10-1980',
    orderStartDate: '01-05-2021',
    orderEndDate: '01-05-2022',
    specials: 'no',
    offenceRisk: false,
  } as IntegrityOrderDetails,
]

const defaultGetSearchResultsOptions = {
  queryExecutionId: 'query-execution-id',
  httpStatus: 200,
  results: defaultOrders,
} as GetSearchResultsStubOptions

type GetSearchResultsStubOptions = {
  queryExecutionId: string
  httpStatus: number
  results: IntegrityOrderDetails[]
}

export const stubGetIntegritySearchResults = (
  options: GetSearchResultsStubOptions = defaultGetSearchResultsOptions,
): SuperAgentRequest =>
  stubFor({
    request: {
      method: 'GET',
      url: `/datastore/orders/integrity?id=${options.queryExecutionId}`,
    },
    response: {
      status: options.httpStatus,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: options.httpStatus === 200 ? options.results : null,
    },
  })

export default stubGetIntegritySearchResults
