export enum Page {
  START = 'START',

  ORDER_SEARCH = 'ORDER_SEARCH',
  ORDER_SEARCH_RESULTS = 'ORDER_SEARCH_RESULTS',

  INTEGRITY_ORDER_SUMMARY = 'INTEGRITY_ORDER_SUMMARY',
  INTEGRITY_ORDER_DETAILS = 'INTEGRITY_ORDER_DETAILS',
  INTEGRITY_VISIT_HISTORY = 'INTEGRITY_VISIT_HISTORY',
  INTEGRITY_EQUIPMENT_HISTORY = 'INTEGRITY_EQUIPMENT_HISTORY',
  INTEGRITY_SERVICE_HISTORY = 'INTEGRITY_SERVICE_HISTORY',
  INTEGRITY_EVENT_HISTORY = 'INTEGRITY_EVENT_HISTORY',
  INTEGRITY_SUSPENSION_OF_VISITS = 'INTEGRITY_SUSPENSION_OF_VISITS',

  ALCOHOL_MONITORING_ORDER_SUMMARY = 'ALCOHOL_MONITORING_ORDER_SUMMARY',
  ALCOHOL_MONITORING_ORDER_DETAILS = 'ALCOHOL_MONITORING_ORDER_DETAILS',
  ALCOHOL_MONITORING_VISIT_HISTORY = 'ALCOHOL_MONITORING_VISIT_HISTORY',
  ALCOHOL_MONITORING_EQUIPMENT_HISTORY = 'ALCOHOL_MONITORING_EQUIPMENT_HISTORY',
  ALCOHOL_MONITORING_SERVICE_HISTORY = 'ALCOHOL_MONITORING_SERVICE_HISTORY',
  ALCOHOL_MONITORING_EVENT_HISTORY = 'ALCOHOL_MONITORING_EVENT_HISTORY',

  API_CONNECTION_TEST = 'API_CONNECTION_TEST',
}

export default Page
