export enum Page {
  START = 'START',
  SEARCH = 'SEARCH',
  SEARCH_RESULTS = 'SEARCH_RESULTS',
  API_CONNECTION_TEST = 'API_CONNECTION_TEST',

  INTEGRITY_ORDER_SUMMARY = 'INTEGRITY_ORDER_SUMMARY',
  INTEGRITY_ORDER_DETAILS = 'INTEGRITY_ORDER_DETAILS',
  INTEGRITY_VISIT_DETAILS = 'INTEGRITY_VISIT_DETAILS',
  INTEGRITY_EQUIPMENT_DETAILS = 'INTEGRITY_EQUIPMENT_DETAILS',
  INTEGRITY_SERVICE_DETAILS = 'INTEGRITY_SERVICE_DETAILS',
  INTEGRITY_EVENT_HISTORY = 'INTEGRITY_EVENT_HISTORY',
  INTEGRITY_SUSPENSION_OF_VISITS = 'INTEGRITY_SUSPENSION_OF_VISITS',

  ALCOHOL_MONITORING_ORDER_SUMMARY = 'ALCOHOL_MONITORING_ORDER_SUMMARY',
  ALCOHOL_MONITORING_ORDER_DETAILS = 'ALCOHOL_MONITORING_ORDER_DETAILS',
  ALCOHOL_MONITORING_VISIT_DETAILS = 'ALCOHOL_MONITORING_VISIT_DETAILS',
  ALCOHOL_MONITORING_EQUIPMENT_DETAILS = 'ALCOHOL_MONITORING_EQUIPMENT_DETAILS',
  ALCOHOL_MONITORING_SERVICE_DETAILS = 'ALCOHOL_MONITORING_SERVICE_DETAILS',
  ALCOHOL_MONITORING_EVENT_HISTORY = 'ALCOHOL_MONITORING_EVENT_HISTORY',
}

export default Page
