export enum HMPPS_AUTH_ROLES {
  ROLE_EM_DATASTORE_GENERAL__RO = 'ROLE_EM_DATASTORE_GENERAL_RO',
  ROLE_EM_DATASTORE_RESTRICTED__RO = 'ROLE_EM_DATASTORE_RESTRICTED_RO',
}

export default HMPPS_AUTH_ROLES
